version: '3.3'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 8
    volumes:
      - ./app/:/app/
    ports:
      - 8000:8000
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web